version: '2'
services:
  db:
    image: postgres
    # volumes_from: 
    #   - data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    # env_file:
    #   - '.env'
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
  app:
    links:
      - db
    build: .
    image: rails:demo
    volumes:
      - .:/var/app
    ports:
      - '4000:3000'
    # command: [bundle, exec, puma]
    command: rails server -b 0.0.0.0 -p 3000
    env_file: 
      - .env
